apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: WORKSHOP
        - name: POSTGRES_PASSWORD
          value: postgres
        image: postgres
        name: database
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/z99_dump.sql
          name: database-claim0
      restartPolicy: Always
      volumes:
      - name: database-claim0
        persistentVolumeClaim:
          claimName: database-claim0
status: {}
