apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-server
  name: ksql-server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ksql-server
    spec:
      containers:
      - env:
        - name: KSQL_BOOTSTRAP_SERVERS
          value: kafka1:9092
        - name: KSQL_CUB_KAFKA_TIMEOUT
          value: "300"
        - name: KSQL_KSQL_CACHE_MAX_BYTES_BUFFERING
          value: "10000000"
        - name: KSQL_KSQL_COMMIT_INTERVAL_MS
          value: "2000"
        - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
          value: http://schemaregistry:8081
        - name: KSQL_KSQL_SERVICE_ID
          value: kafka_workshop
        - name: KSQL_KSQL_STREAMS_AUTO_OFFSET_RESET
          value: earliest
        - name: KSQL_LISTENERS
          value: http://0.0.0.0:8088
        image: confluentinc/cp-ksql-server:5.0.0
        name: ksql-server
        ports:
        - containerPort: 8088
        resources: {}
      restartPolicy: Always
status: {}
