apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: schemaregistry
  name: schemaregistry
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: schemaregistry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schemaregistry
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: zookeeper:2181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        image: confluentinc/cp-schema-registry:5.0.0
        name: schemaregistry
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
